Parameters:

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Aruncf
  
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 97.0.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 97.0.1.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 97.0.2.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 97.0.3.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 97.0.4.0/24

  KeyName:
    Description: Key name for resource creation
    Type: String
    Default: amohandas@presisio.com@pscg-training key pair
  
  ImageId:
    Description: AMI Id for ec2 instance creation
    Type: String
    Default : ami-0ed9277fb7eb570c9
  
  InstanceType:
    Description: Instance Type for ec2 instance creation
    Type: String
    Default : t2.micro  

Resources:
  EnvironmentSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://ak-cloudformationstacks.s3.amazonaws.com/networks.yaml
      Parameters:
        EnvironmentName : !Ref  EnvironmentName
        VpcCIDR : !Ref VpcCIDR
        PublicSubnet1CIDR : !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR : !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR : !Ref  PrivateSubnet1CIDR
        PrivateSubnet2CIDR : !Ref PrivateSubnet2CIDR

  WebServerSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://ak-cloudformationstacks.s3.amazonaws.com/webserver.yaml
      Parameters:
        EnvironmentName : !Ref  EnvironmentName
        ImageId: !Ref ImageId
        KeyName : !Ref KeyName
        InstanceType : !Ref InstanceType
        VPC : !GetAtt EnvironmentSubStack.Outputs.VPC
        PublicSubnet1 : !GetAtt EnvironmentSubStack.Outputs.PublicSubnet1
        PublicSubnet2 : !GetAtt EnvironmentSubStack.Outputs.PublicSubnet2

# Outputs:
#   PublicIp:
#     Description: Server Public IP
#     Value: !GetAtt WebServerSubStack.Outputs.PublicIp

