Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  
  KeyName:
    Description: Key name for resource creation
    Type: String
  
  ImageId:
    Description: AMI Id for ec2 instance creation
    Type: String
  
  InstanceType:
    Description: Instance Type for ec2 instance creation
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
 
  EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
          ImageId: !Ref ImageId
          KeyName: !Ref KeyName
          InstanceType: !Ref InstanceType
          SubnetId: !Ref PublicSubnet1
          SecurityGroupIds:
          - !Ref Ec2SecurityGroup
          UserData:
            Fn::Base64: !Sub |
              #!/bin/bash
              yum install httpd -y
              service httpd start  
              echo "<html><body><h1>Hello World<h1></body></html>" > /var/www/html/index.html  
          Tags:
          - Key: Name
            Value: !Sub ${EnvironmentName} Ec2 instance 

  Ec2SecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Enable HTTP and SSH 
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        VpcId: !Ref VPC

# Outputs:
# PublicIp:
#   Description: Server Public IP
#   Value: !GetAtt EC2Instance.PublicIp